spring.application.name=Vjezba4
logging.level.org.springframework.web=DEBUG
server.port=8081
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb